import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavMenu from "./NavMenu";

export const metadata: Metadata = {
  title: "Next Space Forum",
  description: "Generated by next for Developers and Readers",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavMenu/>
        {children}
      </body>
    </html>
  );
}
